name: Bug
description: Report a reproducible defect
title: 'fix: '
labels: ['type:bug']
body:
  - type: textarea
    id: actual
    attributes:
      label: Current behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
    validations:
      required: true
